### ISSUE TITLE
How to use v. 2.62.1 of Docfx?

### ISSUE THREAD

**Issue by otykier** [nikeee/docfx-action#18]
First of all, thanks for creating this. Makes it super easy to use Docfx as part of a GitHub action.

I tried creating a fork of this project, in order to use the newest version of [Docfx, 2.62.1](https://github.com/dotnet/docfx/releases/tag/v2.62.1), but I was unable to make it work. Other than updating the Dockerfile definition with the new URL of the .zip, what else would be needed?

**Comment by SeanKilleen** [comment]
@otykier I just happened to see this. You might want to check out our fork at https://GitHub.com/NUnit/docfx-action. It uses a recent version.

**Comment by nikeee** [comment]
Yeah, you should probably use the docfx action of the NUnit project. I don't have the time/resources to maintain this project in a similar fashion like awesome people like @SeanKilleen ad NUnit.

I've added a maintainance note to the readme. But since this action is used by ~500 repos, I'd still accept patches instead of archiving it. Most probably, we should backport some fixes made in the NUnit fork.
